### ISSUE TITLE
Add openFPGALoader to the hdl/conda-prog repository

### ISSUE THREAD

**Issue by mithro** [trabucayre/openFPGALoader#103]
It would be great to have openFPGALoader in conda for people to use. We maintain a repository of programming tools @ https://github.com/hdl/conda-prog/tree/master/tools and it would be awesome to have it there.

**Comment by trabucayre** [comment]
Really good idea!
Need to read others tools to see how to do that (I'm not familiar with conda) and I send a PR.
thanks

**Comment by umarcor** [comment]
Refs:

- https://github.com/hdl/conda-prog/pull/22
- https://github.com/SymbiFlow/symbiflow-arch-defs/pull/2240

/cc @lpawelcz

**Comment by trabucayre** [comment]
both PR have been merged. I think it's time to close this issue ?
Thanks @mithro @umarcor
