### ISSUE TITLE
return code is zero for some errors

### ISSUE THREAD

**Issue by martin2250** [trabucayre/openFPGALoader#106]
![image](https://user-images.githubusercontent.com/8293473/130442773-eadbfd36-9ee1-439b-9eab-af8aa32409b7.png)
openFPGALoader should always return a non-zero code when the device was not programmed.

**Comment by trabucayre** [comment]
True thanls!
Just because error must throw an exception and it's not done with lattice driver.
Fixed

**Comment by martin2250** [comment]
Thanks for the quick fix!
