### ISSUE TITLE
Handling of verbose

### ISSUE THREAD

**Issue by UweBonnes** [trabucayre/openFPGALoader#110]
Hello,

handling of verbose seem a little "rough". E.g. Jtag sets it unconditionally to false. So there is no way to control message generation in a probe driver.   I think having a possible fine grain debug system is helpfull.

**Comment by trabucayre** [comment]
It's true. In fact jtag verbosity is set to false because this class produce to many "garbage" and it's more a debug mode than a real verbose mode.
I must to cleanup (or simply add a debug mode with a define) to propagate the verbose mode with `--verbose-level`  to have different levels.

**Comment by trabucayre** [comment]
I just pushed a --verbose-level: with value= 2, verbose is enabled for lowlevel drivers.

**Comment by trabucayre** [comment]
Small update: verbose-level is no more converted to bool for jtag drivers -> this let lowlevel driver to have more choice.

It's good to you?

**Comment by trabucayre** [comment]
Can I close this issue? Model is good to you?

**Comment by UweBonnes** [comment]
Yes.

**Comment by UweBonnes** [comment]
Now used in the BMP  WIP
