### ISSUE TITLE
Fix CI errors when job 'Release' is failing

### ISSUE THREAD

**Issue by umarcor** [trabucayre/openFPGALoader#119]
Sometimes GitHub will have connection failures when uploading artifacts as assets to https://github.com/trabucayre/openFPGALoader/releases/tag/nightly. Some files might be incorrectly renamed, which will then fail.
@trabucayre could you please edit the nightly release above and remove any assets including `tmp` in the name? Alternatively, you could just remove all the assets. Then save the release and restart any of the latest CI runs.

**Comment by trabucayre** [comment]
Thanks for this information! I have tried, by myself to find why these failures but I'm definitely a newbie with action...

**Comment by umarcor** [comment]
Actually, this was hard to find if you are not very familiar with the details of the API, which is more than just understanding GitHub Actions. The explanation is in https://github.com/eine/tip/blob/master/tip.py#L134-L142, which is the codebase of one specific Action used in the workflow of this repo. Maybe that snippet can be improved to better handle the situations when `upload_asset` fails...

**Comment by umarcor** [comment]
Closing, because the purpose of the communication is done.

**Comment by trabucayre** [comment]
Thanks to point me script lines.
Yes I have misused "action". It's really interesting/important to have at least a basic idea about this script to be able to fix / have an idea when something fails.

Thanks again.
