### ISSUE TITLE
build from source instructions should have a git clone line

### ISSUE THREAD

**Issue by RGD2** [trabucayre/openFPGALoader#135]
Issue is that a cmake build error happens if the line isn't 

    git clone --recursive https://github.com/trabucayre/openFPGA

... lack of the `--recursive` flag causes cmake to fail with an obscure error ...'does not contain a CMakeLists.txt file.' 
which is obscure for new users.

**Comment by trabucayre** [comment]
Seems to have a mistake (here and in #136) between `openFPGALoader` and `openFPGA`.
For `openFPGA` repository please use [upstream](https://github.com/azonenberg/openfpga) instead of my, a bit old, fork.

Thanks

**Comment by RGD2** [comment]
Sorry! Wasn't aware that there *was* an upstream!
