### ISSUE TITLE
LittleBee flash programming works but reports failure

### ISSUE THREAD

**Issue by pepijndevos** [trabucayre/openFPGALoader#14]
I'm using you tool (414e6ee) to program my Trenz Gowin board, and it actually works, but the tool reports failure. Not sure what is going on actually.

```
Parse pack.fs: Done
erase SRAM Done
Flash SRAM: [==================================================] 100.000000%
Done
SRAM Flash: FAIL
```

**Comment by trabucayre** [comment]
This message is displayed when the checksum in the .fs file (line //CheckSum: 0x) did not match userCode read in the FPGA.
I'm unable to find where I've read this this and maybe I'm wrong to try this test. Are you sure about this entry in your .fs? In all my test with official gowin tool this two values always match.

**Comment by trabucayre** [comment]
By reading the .fs generated by apicula I've seen the header is absent. This is the cause of the "SRAM Flash: FAIL".
ASAP I will try to add this and doing a PR.

**Comment by pepijndevos** [comment]
Apicula does not generate the header comments. It doesn't even generate a checksum in the bitstream. This is ignored by the actual hardware, so I don't bother.

On January 18, 2020 4:32:01 PM GMT+01:00, Gwenhael Goavec-Merou <notifications@github.com> wrote:
>This message is displayed when the checksum in the .fs file (line
>//CheckSum: 0x) did not match userCode read in the FPGA.
>I'm unable to find where I've read this this and maybe I'm wrong to try
>this test. Are you sure about this entry in your .fs? In all my test
>with official gowin tool this two values always match.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/trabucayre/openFPGALoader/issues/14#issuecomment-575908913

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by trabucayre** [comment]
I worked on computing the configuration data checksum. This piece of code (not already pushed) is working the proprietary tool. But with Apicula, where the checksum (first line) is hardcoded, this continue to fail. I know, this information is not mandatory when FPGA is configured to don't check checksum, but I think to add this feature to Apicula to improve support. What is your opinion?

**Comment by pepijndevos** [comment]
I think it'd be a great addition, and would gladly accept a PR.

For myself I'm focused on timing and CI at the moment.

On March 21, 2020 7:24:57 AM GMT+01:00, Gwenhael Goavec-Merou <notifications@github.com> wrote:
>I worked on computing the configuration data checksum. This piece of
>code (not already pushed) is working the proprietary tool. But with
>Apicula, where the checksum (first line) is hardcoded, this continue to
>fail. I know, this information is not mandatory when FPGA is configured
>to don't check checksum, but I think to add this feature to Apicula to
>improve support. What is your opinion?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/trabucayre/openFPGALoader/issues/14#issuecomment-602002485

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by trabucayre** [comment]
Now checksum computation is supported by both openFPGALoader and Apicula, could you confirm me if it's always working and if you're agree I close this issue.
Thanks

**Comment by pepijndevos** [comment]
Yea, I'll test it some time. Might take a few days before I find the time.

**Comment by pepijndevos** [comment]
Works great now.
