### ISSUE TITLE
`openFPGALoader -V` still reports `v0.5.0` on version `0.6.0`

### ISSUE THREAD

**Issue by carlocab** [trabucayre/openFPGALoader#142]
Hi, we're trying to update Homebrew's openFPGALoader to 0.6.0 at https://github.com/Homebrew/homebrew-core/pull/90231.

CI fails upon verifying the output of `openFPGALoader -V`. It seems to still be reporting `0.5.0` with the new version.

It probably comes from here:

https://github.com/trabucayre/openFPGALoader/blob/130060619e1a6689db44f9a66e1aec4eb214ee93/CMakeLists.txt#L5

I'm not sure if this needs to be changed elsewhere, though.

**Comment by trabucayre** [comment]
Thanks @jeanthom for this fix !

**Comment by jeanthom** [comment]
Don't worry, things have been fixed for 0.6.0 with a little bit of patching: https://github.com/Homebrew/homebrew-core/blob/628aed8b9e1e0d95a834615a9ee57c20bf4b6e5d/Formula/openfpgaloader.rb#L24-L29

0.6.1 without the patch is currently under review: https://github.com/Homebrew/homebrew-core/pull/90663

**Comment by trabucayre** [comment]
Great and thanks again!
0.6.1 is a really small minor release: primarly to fix mismatch between version and tag, with actions improvement (without impact for you) and small addition to be compatible with zlib-ng too (when zlib is not found, but again no impact to you).
