### ISSUE TITLE
Olimex ARM-USB-OCD-H

### ISSUE THREAD

**Issue by kimstik** [trabucayre/openFPGALoader#165]
May you add support of subj?

https://github.com/openocd-org/openocd/blob/master/tcl/interface/ftdi/olimex-arm-usb-ocd-h.cfg

```
adapter driver ftdi
ftdi device_desc "Olimex OpenOCD JTAG ARM-USB-OCD-H"
ftdi vid_pid 0x15ba 0x002b

ftdi layout_init 0x0908 0x0b1b
ftdi layout_signal nSRST -oe 0x0200
ftdi layout_signal nTRST -data 0x0100
ftdi layout_signal LED -data 0x0800
```

**Comment by trabucayre** [comment]
[Done](https://github.com/trabucayre/openFPGALoader/commit/fb2aadadad03130c8953b629eaba6b4b40c33153)
Good to you?
Thanks
