### ISSUE TITLE
unknown JTAG ID

### ISSUE THREAD

**Issue by kimstik** [trabucayre/openFPGALoader#167]
I got "JTAG init failed with: Unknown device with IDCODE: 0x0000281b"

You may print a bit more about unknown devices. Like it made here:
https://github.com/openocd-org/openocd/blob/master/src/helper/jep106.inc

`Info : JTAG tap: auto3.tap tap/device found: 0x0000281b (mfg: 0x40d (Gowin Semiconductor Corp), part: 0x0002, ver: 0x0)`

BTW blue looks terrible on black background.. What about options? bw, green?

**Comment by trabucayre** [comment]
It's true. I have to add a better display for unknown device and adding manufacturer ID to help a bit people.
For blue color I have a blak background too :) But I have to search for a ligther blue, green is already used.

0x0000281b is GW2A-55: don't fear when error is displayed for checksum: I have to find howto to compute this one (it's different as GW1N)

**Comment by trabucayre** [comment]
I have pushed commit to improve error message and change blue color.
It's good to you ?
