### ISSUE TITLE
ULX3S: Invalid pin ID

### ISSUE THREAD

**Issue by mole99** [trabucayre/openFPGALoader#249]
Previously I could upload to the ULX3S without problems:

```
> openFPGALoader --board=ulx3s ulx3s.bit
Jtag probe limited to 3MHz
Jtag frequency : requested 6000000Hz -> real 3000000Hz
ret 0
Open file: DONE
Parse file: DONE
Enable configuration: DONE
SRAM erase: DONE
Loading: [==================================================] 100.00%
Done
Disable configuration: DONE
```

But after updating to the latest release, I get:

```
> openFPGALoader --board=ulx3s ulx3s.bit
Invalid pin ID
JTAG init failed with: std::exception
```

My system is: Debian bookworm

I don't have the exact commit where it broke, but I can look for it if needed.

**Comment by trabucayre** [comment]
This regression was introduces when **libgpiod** support was added. pins configuration are now described by it's ID instead of shift (`4` instead of `1 << 4`).
I have pushed a fix: works with my ulx3s but could you confirm?
Thanks

**Comment by mole99** [comment]
Yes, I can confirm that it fixed the issue. Thank you very much :)

**Comment by trabucayre** [comment]
Thanks for your feedback!

**Comment by trabucayre** [comment]
I did not have planned to create a new release soon, but it's true with this regression now fixed and GW2A's MSPI mode added it make sense to create at leas a minor release (0.9.1).
I will doing that ASAP.
Thanks!

**Comment by trabucayre** [comment]
@carlosedp with a bit of late: done!
Thanks!

**Comment by carlosedp** [comment]
Thanks, sent a PR bumping Homebrew.
https://github.com/Homebrew/homebrew-core/compare/master...carlosedp:homebrew-core:patch-1

**Comment by trabucayre** [comment]
Thanks!
