### ISSUE TITLE
Minor cable identification inconsistency?

### ISSUE THREAD

**Issue by inkdot7** [trabucayre/openFPGALoader#276]
In `cable.hpp`, the only occurance of `0x0403:0x6001` is named `ft232RL`

https://github.com/trabucayre/openFPGALoader/blob/938755becb6cab9fb73175a073cc2c5385ed70fc/src/cable.hpp#L103

but in `libusb_ll.cpp` it is named `ft2232RL` (note the extra 2)

https://github.com/trabucayre/openFPGALoader/blob/938755becb6cab9fb73175a073cc2c5385ed70fc/src/libusb_ll.cpp#L71-L72

is that a misprint or intentional (comment in `libusb_ll.cpp` would probably be good)?

**Comment by trabucayre** [comment]
Good catch! Fixed!
Thanks!
