### ISSUE TITLE
Possible mistake assigning _holdn instead of _wpn in ftdispi.cpp

### ISSUE THREAD

**Issue by randyrossi** [trabucayre/openFPGALoader#277]
https://github.com/trabucayre/openFPGALoader/blob/175312423c60484039de339b0df3e52bcd36818f/src/ftdispi.cpp#L97

Is this a typo?  Should this be assigning _wpn instead of _holdn ?

**Comment by trabucayre** [comment]
Good catch! thanks!
Fixed now
