### ISSUE TITLE
SPIFlash::dump should print EDID

### ISSUE THREAD

**Issue by UweBonnes** [trabucayre/openFPGALoader#282]
Adding  read_id(); to the beginning of SPIFlash::dump will print out the EDID found as is helpfull to see nondestructive if communication with the flash works. Please consider something like this.

**Comment by UweBonnes** [comment]
Fixed in head. Sorry for the noise!

**Comment by trabucayre** [comment]
Sorry for delay.
Yes now `read_id` is always called at constructor level.
