### ISSUE TITLE
Support FT232H

### ISSUE THREAD

**Issue by esemwy** [trabucayre/openFPGALoader#34]
Any chance you could add support for the FT232H, like the Adafruit breakout board? I understand they only have a single channel, unlike the FT2232, but they’re cheap and ubiquitous. I specifically want to use it with my ECP5 evaluation board.

**Comment by trabucayre** [comment]
this adapter is already supported.
I know it's not explicitly mentioned in the README and the entry in src/cable.hpp is a bit ambiguous because it's called ft232 instead of ft232h.

**Comment by esemwy** [comment]
Quick answer! thanks! I’ll give it a shot this evening.
