### ISSUE TITLE
Add a release?

### ISSUE THREAD

**Issue by FFY00** [trabucayre/openFPGALoader#37]
Hey, would it be possible to add a release so that I can package this in the Arch Linux repos?

**Comment by trabucayre** [comment]
Done.
Thanks for the motivation to create a version instead of waiting indefinitely

**Comment by FFY00** [comment]
No worries, I've pushed a package to the arch repos :grin:.

https://www.archlinux.org/packages/community/x86_64/openfpgaloader/

**Comment by trabucayre** [comment]
awesome! thank you very much!!
