### ISSUE TITLE
unable to open ftdi device: -4 (usd_open() failed) on Windows (tangnano1k)

### ISSUE THREAD

**Issue by alain6666** [trabucayre/openFPGALoader#411]
I use openFPGALoader from yosys-oss-cad-suite on Windows. When I connect to tangnano1k via USB cable, I enter the command `openFPGALoader. exe - b tangnano1k .\Top.fs`, then, 
```
unable to open ftdi device: -4 (usd_open() failed)
JTAG init failed with: unable to open ftdi device.
```
I think my USB device is recognized properly because when I remove the board connection and enter the above command, it will prompt: 
```
unable to open ftdi device: -3 (device not found)
JTAG init failed with: unable to open ftdi device.
```
![image](https://github.com/trabucayre/openFPGALoader/assets/104855352/ef8e2b1e-3728-49fe-8121-5a609866f8aa)

When I connect the board, the following content will be displayed in my device manager
![image](https://github.com/trabucayre/openFPGALoader/assets/104855352/ecf56528-8ed4-4d38-acd3-0c7218b1d14d)

Additionally, I believe that my board is functioning properly as I can use OpenFPGALoader to burn bitstream normally under MacOS.

**Comment by angelaacabral** [comment]
Hello,

Did you manage to find out what was happening? I have the same problem.

If you are working from Windows, you need Zadig. So, launching the executable worked for me. However, when installing openFPGALoader and running it, I get the same problem.

> openFPGALoader -b gatemate_evb_jtag blink.cfg.bit
empty
unable to open ftdi device: -3 (device not found)
JTAG init failed with: unable to open ftdi device

Thanks.

**Comment by trabucayre** [comment]
Yes, for windows you have to use zadig (and my knowledge stop more or less here for this OS).

@angelaacabral it's weird. If you are able to use openFPGALoader with a tangnano you must be able to do the same thing for the gatemate. Both uses interfaceA for programming.

**Comment by angelaacabral** [comment]
It's quite strange. When I do it with the example zip provided by Cologne Chip, since it has the executable it works correctly, but when installing the tool and executing exactly the same command that is carried out from the Makefile, it gives that error. I have tried changing USB and user permissions, but there is no way.

I had faith that someone would find a solution. In the meantime I will continue investigating.

**Comment by trabucayre** [comment]
And with nightly/release asset it's the same result ?

**Comment by angelaacabral** [comment]
mmm I don't think I know how that would be done.

**Comment by alain6666** [comment]
> Hello,
> 
> Did you manage to find out what was happening? I have the same problem.
> 
> If you are working from Windows, you need Zadig. So, launching the executable worked for me. However, when installing openFPGALoader and running it, I get the same problem.
> 
> > openFPGALoader -b gatemate_evb_jtag blink.cfg.bit
> > empty
> > unable to open ftdi device: -3 (device not found)
> > JTAG init failed with: unable to open ftdi device
> 
> Thanks.

After using Zadig, I can now use OpenFPGALaoader normally.

**Comment by angelaacabral** [comment]
I have already gotten it to work, thank you very much for your help.

**Comment by angelaacabral** [comment]
Certainly, does anyone know if the GateMate primitives' code can be found anywhere? No matter how much I search, I haven't been able to locate them, and I think they are necessary for GHDL.

**Comment by trabucayre** [comment]
@alain6666 : great!
@angelaacabral : synthesis is done by yosys. primitives are in yosys share directory. Check @colognechip config.mk to see how to use it
