### ISSUE TITLE
Cannot find board tangprimer25k 

### ISSUE THREAD

**Issue by pradheepkaliraj** [trabucayre/openFPGALoader#441]
Hi,

I want to use openFPGALoaded for tangprimer25k. The tool couldn't find thisboard. 
Any suggestions on how to use tang primer 25k dock will be much appreciated.

CMD : openFPGALoader -b tangprimer25k impl/pnr/fpga_project.fs
Error: cannot find board 'tangprimer25k'

**Comment by trabucayre** [comment]
Hi,
Could you share openFPGALoader's version?

This board was introduces after v0.11.0 released.

**Comment by pradheepkaliraj** [comment]
Hi, 

sorry for the delay. 

I have the following version.
openFPGALoader v0.11.0. 

Is there a latest version after this?

**Comment by pradheepkaliraj** [comment]
I see that there is a v.0.12.0.
I will try with that once I get permissions to install it.

**Comment by pradheepkaliraj** [comment]
"sudo pacman -S openFPGALoader"  always installs the version v0.11.0.

I uninstalled openFPGALoader with the following command
 sudo pacman -R openFPGALoader

Can you please tell me how to get Version [v0.12.1](https://github.com/trabucayre/openFPGALoader/releases/tag/v0.12.1)

**Comment by trabucayre** [comment]
Could you try to build openFPGALoader from sources?
Or with assets ?

**Comment by trabucayre** [comment]
Any news/update?

**Comment by pradheepkaliraj** [comment]
Thanks for following up. 

I tried to build from the source. But I am getting this error message after cmake --

 "-   No package 'libftdi1' found".

However, when I install libftdi1, I see that it is already installed "libftdi1 is already the newest version."

I am trying to figure out what is going on.

**Comment by trabucayre** [comment]
@pradheepkaliraj any news?

**Comment by pradheepkaliraj** [comment]
Hi, 

Thanks for checking. I was able to install the latest version.
I am able to program Tang25k with the latest version.

**Comment by trabucayre** [comment]
Thanks for your feedback!
