### ISSUE TITLE
Device Not Recognized on Windows Without Using Zadig

### ISSUE THREAD

**Issue by freshmakerzhao** [trabucayre/openFPGALoader#487]
I compiled the project using MSYS2 and attempted to run it on Windows. However, the application fails to recognize the device unless I install the driver using Zadig. After installing the driver with Zadig, the device is recognized, and the download process works correctly.

Is there an alternative method to complete this process without relying on external programs like Zadig?

**Comment by trabucayre** [comment]
Unfortunately with windows and MSYS2 Zadig can't be avoided. I'm not a windows specialist  but it's maybe not required when using WSL2 (but you have to install a quite full GNU/Linux distribution to avoid to install one program...).

**Comment by ZhiyuanYuanNJ** [comment]
> I compiled the project using MSYS2 and attempted to run it on Windows. However, the application fails to recognize the device unless I install the driver using Zadig. After installing the driver with Zadig, the device is recognized, and the download process works correctly.
> 
> Is there an alternative method to complete this process without relying on external programs like Zadig?

There's no other way, hardware work requires drivers, so if you don't use manufacturer drivers, you can only use Zadig's winUSB driver.

**Comment by trabucayre** [comment]
Thanks @ZhiyuanYuanNJ 
@freshmakerzhao It's fine for you. Can I close this issue?

**Comment by freshmakerzhao** [comment]
@ZhiyuanYuanNJ，@trabucayre 
Thank you both for your help. You can close the issue now.
