### ISSUE TITLE
gatemate-evb : unable to open ftdi device

### ISSUE THREAD

**Issue by Suk1268** [trabucayre/openFPGALoader#495]
i have been trying to configure FPGA of the olimex gatemateA1-EVB where i'm getting the following error
![image](https://github.com/user-attachments/assets/406ac2d8-0374-4d96-a2cd-37c74b3e4bfd)

i am able to detect in the device manager after using zadig 
![image](https://github.com/user-attachments/assets/410a4f1a-e391-4310-9696-4d0ee9370676)

i have also referred this git issue (https://github.com/trabucayre/openFPGALoader/issues/245#issue-1337570131)
but the error persists

**Comment by trabucayre** [comment]
Examples and scripts shipped with colognechip toolchain are targeted for CologneChip's gatemateEVB board.
Your board is an olimex with a different JTAG interface and a different pin mapping so you have to use the correct target.
For openFPGALoader you have to use `-b olimex_gatemateevb`

**Comment by Suk1268** [comment]
thank you for the help.
