### ISSUE TITLE
artix-7 200t devices

### ISSUE THREAD

**Issue by GbGp** [trabucayre/openFPGALoader#55]
Hi, I wanted to report that I have tested this software on a artix-7 200t device and so far it seems to work.
Using an FT2232 as download cable I only had to define the new part `{0x13636093, {"xilinx", "artix a7 200t", "xc7a200"}}`.

I only had some issues for the digilent nexys video board, where apparently the jtag is connected on the INTERFACE_B of the integrated FT2232 chip. So I just defined a new download cable `{"digilentb",    {MODE_FTDI_SERIAL,  {0x0403, 0x6010, INTERFACE_B, 0xe8, 0xeb, 0x00, 0x60}}}`

**Comment by trabucayre** [comment]
Great!
For JTAG interface, it's possible to use --ftdi-channel 2 to have the same effect, but it make sense to have a cable definition like this one.
Would you like to create a PR to add an entry in for this FPGA, for the board and the cable or you want I add this myself?
Thank for your feedback

**Comment by GbGp** [comment]
Today I could also test programming the flash on the nexys video, looks fine as well. I made a PR.

**Comment by trabucayre** [comment]
Thanks for the PR.
Can I close this issue ?

**Comment by GbGp** [comment]
sure, thanks.
