### ISSUE TITLE
No color option

### ISSUE THREAD

**Issue by Martoni** [trabucayre/openFPGALoader#6]
Color output is great, but sometimes we need no color (for logging, old terminal, ...).
It could be good to add nocolor option.

**Comment by FFY00** [comment]
Deciding in outputting color based on `isatty` is usually enough, would that work for your use case?

**Comment by trabucayre** [comment]
I have added `isatty`, as mentioned by @FFY00,  in display.cpp, to drop color when output is not a terminal.

It's good for you ?

**Comment by Martoni** [comment]
seems to be good yes.
