### ISSUE TITLE
Tested on Xilinx Spartan7 (xc7s25)

### ISSUE THREAD

**Issue by dbellix** [trabucayre/openFPGALoader#60]
Hi,
I've added the following line to ../src/part.hpp:

{0x037c4093, {"xilinx", "spartan7", "xc7s25csga225"}},

and successfully loaded a bitfile inside the aforementioned spartan7. Maybe it could be good for others to add this to the main branch.

Best,
dbellix

**Comment by trabucayre** [comment]
I've updated part.hpp and README.md with this ref.

Thanks
