### ISSUE TITLE
Detect works but "Unknown device family" when trying to program

### ISSUE THREAD

**Issue by kargeor** [trabucayre/openFPGALoader#88]
I have tried both with dirty-jtag (blue pill) and ft232RL.
Tried 2 FPGA families: XO2 and ECP5.

--detect works fine and gives me the device info correctly.

When I try to program the second time the device id is read, results are garbage causing "Unknown device family" error.
-v prints the correct device ID during programming.

OS: macOS Big Sur Latest.
Tried latest master and older versions.

**Comment by trabucayre** [comment]
Which board you use ?
With these interface I assume you use "dupont" cable? Could you check wires, It's usually a source of problem/glitches.
Sometime pullup and pulldown are required to have stable signals
Thanks

**Comment by kargeor** [comment]
I am using a custom built board. Yes, "dupont" cables. 😃 
Turns out adding a resistor to TDO fixed all problems. Maybe add a note in the docs?
Also added the XO2 part I'm using [here](https://github.com/trabucayre/openFPGALoader/pull/89/files)

**Comment by trabucayre** [comment]
It's true I must add warning about "dupont" cables and pullup/pulldown resistors.
Maybe adding a FAQ somewhere with common issues will be a good feature too.

Thanks for you feedback

**Comment by DoctorMikeReddy** [comment]
What value resistor was used on the TDO line?

**Comment by kargeor** [comment]
1k or 10k.

**Comment by stefan63** [comment]
TDO pullup or down?
Kind regards/Stefan
